/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package forme;

import domen.Gost;
import domen.TipGosta;
import izuzeci.GasenjeProgramaIzuzetak;
import izuzeci.ServerskiIzuzetak;
import java.util.List;
import javax.swing.JOptionPane;
import kontroler.Kontroler;

/**
 *
 * @author Joska Stojanovic
 */
public class FormaGost extends javax.swing.JDialog {

    private Gost izabraniGost;
    private StatusForme status;

    /**
     * Creates new form FormaGost
     */
    public FormaGost(FormaZaPretraguGostiju parent, boolean modal, StatusForme statusForme, Gost gost) {
        super(parent, modal);
        initComponents();
        this.izabraniGost = gost;
        this.status = statusForme;
        pripremiFormu(statusForme);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblImeGosta = new javax.swing.JLabel();
        lblPrezimeGosta = new javax.swing.JLabel();
        lblTipGosta = new javax.swing.JLabel();
        txtImeGosta = new javax.swing.JTextField();
        txtPrezimeGosta = new javax.swing.JTextField();
        cmbTipGosta = new javax.swing.JComboBox();
        lblIDGost = new javax.swing.JLabel();
        txtIDGost = new javax.swing.JTextField();
        btnOtkazi = new javax.swing.JButton();
        btnDugme = new javax.swing.JButton();
        btnObrisi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Gost"));

        lblImeGosta.setText("Ime gosta:");

        lblPrezimeGosta.setText("Prezime gosta:");

        lblTipGosta.setText("Tip gosta:");

        cmbTipGosta.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbTipGosta.setSelectedIndex(-1);

        lblIDGost.setText("ID:");

        btnOtkazi.setText("Otkazi");
        btnOtkazi.addActionListener(this::btnOtkaziActionPerformed);

        btnDugme.setText("Dugme");
        btnDugme.addActionListener(this::btnDugmeActionPerformed);

        btnObrisi.setText("Obrisi");
        btnObrisi.addActionListener(this::btnObrisiActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblImeGosta)
                            .addComponent(lblPrezimeGosta)
                            .addComponent(lblTipGosta)
                            .addComponent(lblIDGost))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtImeGosta)
                            .addComponent(txtPrezimeGosta)
                            .addComponent(cmbTipGosta, 0, 335, Short.MAX_VALUE)
                            .addComponent(txtIDGost, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnObrisi, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnOtkazi, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnDugme, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(19, 19, 19))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIDGost)
                    .addComponent(txtIDGost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblImeGosta)
                    .addComponent(txtImeGosta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPrezimeGosta)
                    .addComponent(txtPrezimeGosta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTipGosta)
                    .addComponent(cmbTipGosta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnObrisi)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnDugme)
                        .addComponent(btnOtkazi)))
                .addGap(35, 35, 35))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOtkaziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOtkaziActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnOtkaziActionPerformed

    private void btnDugmeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDugmeActionPerformed

        // PRIKAZ
        if (status == StatusForme.PRIKAZI) {
            this.dispose();
            FormaGost formaGostIzmena = new FormaGost((FormaZaPretraguGostiju) this.getParent(), true, StatusForme.IZMENI, izabraniGost);
            formaGostIzmena.setVisible(true);
            return;
        }

        // DODAVANJE/IZMENA
        String imeGosta = txtImeGosta.getText().trim();
        String prezimeGosta = txtPrezimeGosta.getText().trim();
        TipGosta tipGosta = (TipGosta) cmbTipGosta.getSelectedItem();

        if (imeGosta.isEmpty() || prezimeGosta.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Morate popuniti sva polja!", "Upozorenje", JOptionPane.WARNING_MESSAGE);
            return;
        }
        izabraniGost.setImeGosta(imeGosta);
        izabraniGost.setPrezimeGosta(prezimeGosta);
        izabraniGost.setTipGosta(tipGosta);

        try {
            Kontroler.getInstanca().izmeniGosta(izabraniGost);
            JOptionPane.showMessageDialog(this, "Sistem je zapamtio gosta.", "Uspeh", JOptionPane.INFORMATION_MESSAGE);

            if (getParent() instanceof FormaZaPretraguGostiju) {
                ((FormaZaPretraguGostiju) getParent()).srediTabelu();
            }

            this.dispose();

        } catch (GasenjeProgramaIzuzetak ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Upozorenje", JOptionPane.WARNING_MESSAGE);
            System.exit(0);
        } catch (ServerskiIzuzetak ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Greska prilikom izmene gosta", JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Doslo je do neocekivane greske prilikom izmene gosta.", "Greska prilikom izmene gosta", JOptionPane.ERROR_MESSAGE);
        }


    }//GEN-LAST:event_btnDugmeActionPerformed

    private void btnObrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiActionPerformed
        try {

            Kontroler.getInstanca().obrisiGosta(izabraniGost.getIdGost());
            JOptionPane.showMessageDialog(this, "Sistem je obrisao gosta.", "Brisanje gosta", JOptionPane.INFORMATION_MESSAGE);

            FormaZaPretraguGostiju formaZaPretragu = (FormaZaPretraguGostiju) getParent();
            formaZaPretragu.srediTabelu();
            this.dispose();

        } catch (GasenjeProgramaIzuzetak ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Upozorenje", JOptionPane.WARNING_MESSAGE);
            System.exit(0);
        } catch (ServerskiIzuzetak ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Greska prilikom brisanja gosta", JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Doslo je do neocekivane greske prilikom brisanja izabranog gosta.", "Greska prilikom brisanja gosta", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnObrisiActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDugme;
    private javax.swing.JButton btnObrisi;
    private javax.swing.JButton btnOtkazi;
    private javax.swing.JComboBox cmbTipGosta;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblIDGost;
    private javax.swing.JLabel lblImeGosta;
    private javax.swing.JLabel lblPrezimeGosta;
    private javax.swing.JLabel lblTipGosta;
    private javax.swing.JTextField txtIDGost;
    private javax.swing.JTextField txtImeGosta;
    private javax.swing.JTextField txtPrezimeGosta;
    // End of variables declaration//GEN-END:variables

    private void pripremiFormu(StatusForme statusForme) {
        
        popuniTipGosta();
        setLocationRelativeTo(null);
        txtIDGost.setEnabled(false);

        switch (statusForme) {
            case DODAJ:
                btnObrisi.setVisible(false);
                btnDugme.setText("Sacuvaj");
                txtImeGosta.setText("");
                txtPrezimeGosta.setText("");
                txtIDGost.setText(String.valueOf(izabraniGost.getIdGost()));
                setTitle("Forma za dodavanje novog gosta");
                
                setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
                break;

            case PRIKAZI:
                btnDugme.setText("Izmeni");
                txtImeGosta.setEnabled(false);
                txtPrezimeGosta.setEnabled(false);
                cmbTipGosta.setEnabled(false);
                popuniPoljaZaIzabranogGosta(izabraniGost);
                setTitle("Forma za prikaz gosta");
                break;

            case IZMENI:
                btnObrisi.setVisible(false);
                btnDugme.setText("Potvrdi izmene");
                popuniPoljaZaIzabranogGosta(izabraniGost);
                setTitle("Forma za izmenu gosta");
                break;
        }
    }

    private void popuniTipGosta() {
        try {
            cmbTipGosta.removeAllItems();
            List<TipGosta> tipovi = Kontroler.getInstanca().vratiSveTipoveGosta();

            for (TipGosta tipGosta : tipovi) {
                cmbTipGosta.addItem(tipGosta);
            }
        } catch (GasenjeProgramaIzuzetak ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Upozorenje", JOptionPane.WARNING_MESSAGE);
            System.exit(0);
        } catch (ServerskiIzuzetak ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Greska prilikom ucitavanja tipova gosta", JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Doslo je do neocekivane greske prilikom ucitavanja tipova gosta.", "Greska prilikom ucitavanja tipova gosta", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void popuniPoljaZaIzabranogGosta(Gost gost) {
        txtIDGost.setText(String.valueOf(gost.getIdGost()));
        txtImeGosta.setText(gost.getImeGosta());
        txtPrezimeGosta.setText(gost.getPrezimeGosta());
        cmbTipGosta.setSelectedItem(gost.getTipGosta());
    }
}
