/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package forme;

import domen.Kvalifikacija;
import izuzeci.GasenjeProgramaIzuzetak;
import izuzeci.ServerskiIzuzetak;
import javax.swing.JOptionPane;
import kontroler.Kontroler;

/**
 *
 * @author Joska Stojanovic
 */
public class FormaKvalifikacija extends javax.swing.JDialog {
    /**
     * Creates new form FormaKvalifikacija
     */
    public FormaKvalifikacija(java.awt.Frame parent, boolean modal,StatusForme statusForme) {
        super(parent, modal);
        initComponents();
        pripremiFormu(statusForme);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblNazivKvalifikacije = new javax.swing.JLabel();
        txtNazivKvalifikacije = new javax.swing.JTextField();
        btnSacuvaj = new javax.swing.JButton();
        btnOtkazi = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textAreaOpis = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Kvalifikacija"));

        lblNazivKvalifikacije.setText("Naziv kvalifikacije:");

        btnSacuvaj.setText("Sacuvaj");
        btnSacuvaj.addActionListener(this::btnSacuvajActionPerformed);

        btnOtkazi.setText("Otkazi");
        btnOtkazi.addActionListener(this::btnOtkaziActionPerformed);

        jLabel1.setText("Opis: ");

        textAreaOpis.setColumns(20);
        textAreaOpis.setRows(5);
        jScrollPane1.setViewportView(textAreaOpis);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNazivKvalifikacije)
                    .addComponent(jLabel1))
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnOtkazi, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                        .addComponent(btnSacuvaj, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtNazivKvalifikacije, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(14, 14, 14))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNazivKvalifikacije)
                    .addComponent(txtNazivKvalifikacije, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOtkazi)
                    .addComponent(btnSacuvaj))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSacuvajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSacuvajActionPerformed
        String nazivKvalifikacije = txtNazivKvalifikacije.getText();
        String opis=textAreaOpis.getText();

        if (nazivKvalifikacije.isEmpty() || opis.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Morate uneti naziv i opis prilikom dodavanja nove kvalifikacije!", "Dodavanje kvalifikacije", JOptionPane.WARNING_MESSAGE);
            return;
        }

        Kvalifikacija kvalifikacija = new Kvalifikacija(-1, nazivKvalifikacije, opis);

        try {
            Kontroler.getInstanca().dodajKvalifikaciju(kvalifikacija);
            JOptionPane.showMessageDialog(this, "Sistem je zapamtio kvalifikaciju.", "Dodavanje kvalifikacije", JOptionPane.INFORMATION_MESSAGE);
            this.dispose();
        } catch (GasenjeProgramaIzuzetak ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Upozorenje", JOptionPane.WARNING_MESSAGE);
            System.exit(0);
        } catch (ServerskiIzuzetak ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Greska prilikom dodavanja kvalifikacije", JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Doslo je do greske prilikom dodavanja nove kvalifikacije.", "Greska prilikom dodavanja kvalifikacije", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSacuvajActionPerformed

    private void btnOtkaziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOtkaziActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnOtkaziActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOtkazi;
    private javax.swing.JButton btnSacuvaj;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblNazivKvalifikacije;
    private javax.swing.JTextArea textAreaOpis;
    private javax.swing.JTextField txtNazivKvalifikacije;
    // End of variables declaration//GEN-END:variables

    private void pripremiFormu(StatusForme statusForme) {
        setLocationRelativeTo(null);
        switch (statusForme){
            case DODAJ:
                setTitle("Forma za dodavanje nove kvalifikacije");
                break;
        }
    }
}
