/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package forme;

import domen.Gost;
import domen.TipGosta;
import izuzeci.GasenjeProgramaIzuzetak;
import izuzeci.ServerskiIzuzetak;
import java.util.List;
import javax.swing.JOptionPane;
import kontroler.Kontroler;
import modeli.ModelTabeleGost;
/**
 *
 * @author Joska Stojanovic
 */
public class FormaZaPretraguGostiju extends javax.swing.JDialog {

    ModelTabeleGost modelTabeleGost;

    /**
     * Creates new form FormaZaPretraguGostiju
     */
    public FormaZaPretraguGostiju(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        pripremiFormu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmbTipGosta = new javax.swing.JComboBox();
        btnPretrazi = new javax.swing.JButton();
        lblTipGosta = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblGosti = new javax.swing.JTable();
        btnDetalji = new javax.swing.JButton();
        btnOtkazi = new javax.swing.JButton();
        lblImeGosta = new javax.swing.JLabel();
        txtImeGosta = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        cmbTipGosta.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbTipGosta.setSelectedIndex(-1);

        btnPretrazi.setText("Pretrazi");
        btnPretrazi.addActionListener(this::btnPretraziActionPerformed);

        lblTipGosta.setText("Tip gosta:");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder("Gosti"), "Gosti"));

        tblGosti.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblGosti);

        btnDetalji.setText("Detalji o izabranom gostu");
        btnDetalji.addActionListener(this::btnDetaljiActionPerformed);

        btnOtkazi.setText("Otkazi");
        btnOtkazi.addActionListener(this::btnOtkaziActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnOtkazi, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDetalji, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDetalji)
                    .addComponent(btnOtkazi))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        lblImeGosta.setText("Ime gosta: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(lblTipGosta, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbTipGosta, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblImeGosta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtImeGosta, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(44, 44, 44)
                .addComponent(btnPretrazi, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTipGosta)
                            .addComponent(cmbTipGosta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblImeGosta)
                            .addComponent(txtImeGosta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(btnPretrazi, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPretraziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPretraziActionPerformed
        TipGosta tipGosta = (TipGosta) cmbTipGosta.getSelectedItem();
        String ime=txtImeGosta.getText().trim();
        if (tipGosta == null && txtImeGosta.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Morate popuniti tip i/ili ime gosta prilikom pretrage gostiju!", "Pretraga gostiju", JOptionPane.WARNING_MESSAGE);
        } else {
            List<Gost> listaGostiju;
            try {
                listaGostiju = Kontroler.getInstanca().pretraziGoste(tipGosta,ime);

                modelTabeleGost = new ModelTabeleGost();
                tblGosti.setModel(modelTabeleGost);

                if (listaGostiju.isEmpty()) {
                    JOptionPane.showMessageDialog(this, "Sistem ne moze da pronadje goste po zadatim kriterijumima.", "Greska prilikom pretrage gostiju", JOptionPane.ERROR_MESSAGE);
                    return;
                } else {
                    JOptionPane.showMessageDialog(this, "Sistem je nasao goste po zadatim kriterijumima.", "Pretraga gostiju", JOptionPane.INFORMATION_MESSAGE);
                }

                modelTabeleGost.setListaGostiju(listaGostiju);

            } catch (GasenjeProgramaIzuzetak ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage(), "Upozorenje", JOptionPane.WARNING_MESSAGE);
                System.exit(0);
            } catch (ServerskiIzuzetak ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage(), "Greska prilikom pretrage gostiju", JOptionPane.ERROR_MESSAGE);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Doslo je do neocekivane greske prilikom pretrage gostiju.", "Greska prilikom pretrage gostiju", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnPretraziActionPerformed

    private void btnOtkaziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOtkaziActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnOtkaziActionPerformed

    private void btnDetaljiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetaljiActionPerformed
        int izabraniRed = tblGosti.getSelectedRow();

        if (izabraniRed == -1) {
            JOptionPane.showMessageDialog(this, "Morate izabrati gosta iz tabele!", "Detalji o gostu", JOptionPane.WARNING_MESSAGE);
        } else {
            try {
                modelTabeleGost = (ModelTabeleGost) tblGosti.getModel();
                Gost izabraniGost = modelTabeleGost.vratiGosta(izabraniRed);
                
                Gost gost = Kontroler.getInstanca().vratiGosta(izabraniGost.getIdGost());
                JOptionPane.showMessageDialog(this, "Sistem je nasao gosta.", "Detalji o gostu", JOptionPane.INFORMATION_MESSAGE);
                
                FormaGost formaGostPrikaz = new FormaGost(this, true, StatusForme.PRIKAZI,gost);
                formaGostPrikaz.setVisible(true);
                
            } catch (GasenjeProgramaIzuzetak ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage(), "Upozorenje", JOptionPane.WARNING_MESSAGE);
                System.exit(0);
            } catch (ServerskiIzuzetak ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage(), "Greska prilikom ucitavanja gosta", JOptionPane.ERROR_MESSAGE);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Doslo je do neocekivane greske prilikom ucitavanja izabranog gosta.", "Greska prilikom ucitavanja gosta", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnDetaljiActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDetalji;
    private javax.swing.JButton btnOtkazi;
    private javax.swing.JButton btnPretrazi;
    private javax.swing.JComboBox cmbTipGosta;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblImeGosta;
    private javax.swing.JLabel lblTipGosta;
    private javax.swing.JTable tblGosti;
    private javax.swing.JTextField txtImeGosta;
    // End of variables declaration//GEN-END:variables

    private void pripremiFormu() {
        setLocationRelativeTo(null);
        setTitle("Forma za pretragu gostiju");
        popuniTipove();
        srediTabelu();
    }

    private void popuniTipove() {
        try {
            cmbTipGosta.removeAllItems();
            List<TipGosta> tipovi = Kontroler.getInstanca().vratiSveTipoveGosta();
            for (TipGosta tipGosta : tipovi) {
                cmbTipGosta.addItem(tipGosta);
            }
            cmbTipGosta.setSelectedIndex(-1);
        } catch (GasenjeProgramaIzuzetak ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Upozorenje", JOptionPane.WARNING_MESSAGE);
            System.exit(0);
        } catch (ServerskiIzuzetak ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Greska prilikom ucitavanja tipova gosta", JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Doslo je do neocekivane greske prilikom ucitavanja tipova gosta.", "Greska prilikom ucitavanja tipova gosta", JOptionPane.ERROR_MESSAGE);
        }
    }

    public void srediTabelu() {
        try {
            List<Gost> listaGostiju = Kontroler.getInstanca().vratiSveGoste();
            modelTabeleGost = new ModelTabeleGost();
            tblGosti.setModel(modelTabeleGost);

            modelTabeleGost.setListaGostiju(listaGostiju);
        } catch (GasenjeProgramaIzuzetak ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Upozorenje", JOptionPane.WARNING_MESSAGE);
            System.exit(0);
        } catch (ServerskiIzuzetak ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Greska prilikom ucitavanja gostiju", JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Doslo je do neocekivane greske prilikom ucitavanja gostiju.", "Greska prilikom ucitavanja gostiju", JOptionPane.ERROR_MESSAGE);
        }
    }
}
