/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package forme;

import domen.Artikal;
import domen.Gost;
import domen.Konobar;
import domen.NacinPlacanja;
import domen.Narudzbina;
import izuzeci.GasenjeProgramaIzuzetak;
import izuzeci.ServerskiIzuzetak;
import java.math.BigDecimal;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import kontroler.Kontroler;
import modeli.ModelTabeleArtikal;
import modeli.ModelTabeleStavkaNarudzbine;
import sesija.Sesija;

/**
 *
 * @author Joska Stojanovic
 */
public class FormaNarudzbina extends javax.swing.JDialog {

    StatusForme status;
    Narudzbina izabranaNarudzbina;

    /**
     * Creates new form FormaNarudzbina
     */
    public FormaNarudzbina(FormaZaPretraguNarudzbina parent, boolean modal, StatusForme status, Narudzbina izabranaNarudzbina) {
        super(parent, modal);
        initComponents();
        this.status = status;
        this.izabranaNarudzbina = izabranaNarudzbina;
        pripremiFormu(status);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblIDNarudzbenica = new javax.swing.JLabel();
        txtIDNarudzbina = new javax.swing.JTextField();
        lblDatumNarucivanja = new javax.swing.JLabel();
        lblNacinPlacanja = new javax.swing.JLabel();
        cmbGost = new javax.swing.JComboBox();
        lblGost = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblArtikli = new javax.swing.JTable();
        btnDodajStavkuNarudzbine = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblStavkeNarudzbine = new javax.swing.JTable();
        btnObrisiStavkuNarudzbine = new javax.swing.JButton();
        lblUkupanIznos = new javax.swing.JLabel();
        txtUkupanIznos = new javax.swing.JTextField();
        lblKonobar = new javax.swing.JLabel();
        btnDugme = new javax.swing.JButton();
        btnOtkazi = new javax.swing.JButton();
        txtDatumNarucivanja = new javax.swing.JFormattedTextField();
        lblNapomena = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtNapomena = new javax.swing.JTextArea();
        cmbNacinPlacanja = new javax.swing.JComboBox<>();
        cmbKonobar = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Narudzbina"));

        lblIDNarudzbenica.setText("ID:");

        lblDatumNarucivanja.setText("Datum narucivanja:");

        lblNacinPlacanja.setText("Nacin placanja: ");

        cmbGost.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbGost.setSelectedIndex(-1);

        lblGost.setText("Gost:");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Artikli"));

        tblArtikli.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblArtikli);

        btnDodajStavkuNarudzbine.setText("Dodaj izabrani artikal kao stavku narudzbine");
        btnDodajStavkuNarudzbine.addActionListener(this::btnDodajStavkuNarudzbineActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 886, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDodajStavkuNarudzbine, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnDodajStavkuNarudzbine)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Stavke narudzbine"));

        tblStavkeNarudzbine.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblStavkeNarudzbine);

        btnObrisiStavkuNarudzbine.setText("Obrisi izbranu stavku narudzbine");
        btnObrisiStavkuNarudzbine.addActionListener(this::btnObrisiStavkuNarudzbineActionPerformed);

        lblUkupanIznos.setText("Ukupan iznos:");

        txtUkupanIznos.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lblUkupanIznos)
                        .addGap(68, 68, 68)
                        .addComponent(txtUkupanIznos, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnObrisiStavkuNarudzbine, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 884, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnObrisiStavkuNarudzbine)
                    .addComponent(lblUkupanIznos)
                    .addComponent(txtUkupanIznos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        lblKonobar.setText("Kreirao konobar:");

        btnDugme.setText("Dugme");
        btnDugme.addActionListener(this::btnDugmeActionPerformed);

        btnOtkazi.setText("Otkazi");
        btnOtkazi.addActionListener(this::btnOtkaziActionPerformed);

        txtDatumNarucivanja.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd.MM.yyyy"))));

        lblNapomena.setText("Napomena:");

        txtNapomena.setColumns(20);
        txtNapomena.setRows(5);
        jScrollPane3.setViewportView(txtNapomena);

        cmbNacinPlacanja.setModel(new DefaultComboBoxModel<>(NacinPlacanja.values()));
        cmbNacinPlacanja.addActionListener(this::cmbNacinPlacanjaActionPerformed);

        cmbKonobar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblKonobar)
                            .addComponent(lblNapomena))
                        .addGap(72, 72, 72)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(cmbKonobar, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnDugme, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnOtkazi, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblIDNarudzbenica)
                            .addComponent(lblGost))
                        .addGap(57, 57, 57)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmbGost, 0, 255, Short.MAX_VALUE)
                            .addComponent(txtIDNarudzbina))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDatumNarucivanja)
                            .addComponent(lblNacinPlacanja))
                        .addGap(61, 61, 61)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtDatumNarucivanja, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                            .addComponent(cmbNacinPlacanja, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(17, 17, 17))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblIDNarudzbenica)
                            .addComponent(txtIDNarudzbina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbGost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblGost)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNacinPlacanja)
                            .addComponent(cmbNacinPlacanja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblDatumNarucivanja)
                        .addComponent(txtDatumNarucivanja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNapomena)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblKonobar)
                    .addComponent(cmbKonobar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDugme)
                    .addComponent(btnOtkazi))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDodajStavkuNarudzbineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajStavkuNarudzbineActionPerformed
        int izabraniRed = tblArtikli.getSelectedRow();

        if (izabraniRed == -1) {
            JOptionPane.showMessageDialog(this, "Morate izabrati artikal iz tabele!", "Dodavanje narudzbine", JOptionPane.WARNING_MESSAGE);

        } else {
            ModelTabeleArtikal modelTabeleArtikal = (ModelTabeleArtikal) tblArtikli.getModel();
            Artikal izabraniArtikal = modelTabeleArtikal.vratiArtikal(izabraniRed);
            if (!izabraniArtikal.isDostupan()) {
                JOptionPane.showMessageDialog(null, "Artikal nije dostupan!", "Dodavanje narudzbine", JOptionPane.WARNING_MESSAGE);
                return;
            }
            ModelTabeleStavkaNarudzbine modelTabeleStavke = (ModelTabeleStavkaNarudzbine) tblStavkeNarudzbine.getModel();
            modelTabeleStavke.dodajStavku(izabraniArtikal);
        }
    }//GEN-LAST:event_btnDodajStavkuNarudzbineActionPerformed

    private void btnObrisiStavkuNarudzbineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiStavkuNarudzbineActionPerformed
        int izabraniRed = tblStavkeNarudzbine.getSelectedRow();
        if (izabraniRed == -1) {
            JOptionPane.showMessageDialog(this, "Morate izabrati stavku narudzbine iz tabele!", "Dodavanje narudzbine", JOptionPane.WARNING_MESSAGE);
        } else {
            ModelTabeleStavkaNarudzbine modelTabeleStavka = (ModelTabeleStavkaNarudzbine) tblStavkeNarudzbine.getModel();
            modelTabeleStavka.obrisiStavku(izabraniRed);
        }
    }//GEN-LAST:event_btnObrisiStavkuNarudzbineActionPerformed

    private void btnDugmeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDugmeActionPerformed

        // PRIKAZ
        if (status.equals(StatusForme.PRIKAZI)) {
            this.dispose();
            FormaNarudzbina formaNarudzbinaIzmena = new FormaNarudzbina((FormaZaPretraguNarudzbina) this.getParent(), true, StatusForme.IZMENI, izabranaNarudzbina);
            formaNarudzbinaIzmena.setVisible(true);
            return;
        }
        //DODAVANJE
        if (status.equals(StatusForme.DODAJ)) {

            try {
                if (txtDatumNarucivanja.getText().isEmpty()) {
                    throw new Exception("Morate uneti datum naručivanja!");
                }

                SimpleDateFormat sdf = new SimpleDateFormat("dd.MM.yyyy");

                Date datumNarucivanja;
                try {
                    datumNarucivanja = sdf.parse(txtDatumNarucivanja.getText());
                } catch (ParseException ex) {
                    throw new Exception("Neispravan format datuma (dd.MM.yyyy)!");
                }

                Date danas = sdf.parse(sdf.format(new Date()));

                if (datumNarucivanja.after(danas)) {
                    throw new Exception("Datum naručivanja ne sme biti u buducnosti!");
                }

                ModelTabeleStavkaNarudzbine mts
                        = (ModelTabeleStavkaNarudzbine) tblStavkeNarudzbine.getModel();

                if (mts.getListaStavki().isEmpty()) {
                    throw new Exception("Narudžbina mora sadržati barem jednu stavku!");
                }

                Narudzbina narudzbina = new Narudzbina();

                narudzbina.setGost((Gost) cmbGost.getSelectedItem());
                narudzbina.setNacinPlacanja((NacinPlacanja) cmbNacinPlacanja.getSelectedItem());
                narudzbina.setNapomena(txtNapomena.getText());
                narudzbina.setStavkeNarudzbine(mts.getListaStavki());

                narudzbina.setUkupanIznos(new BigDecimal(txtUkupanIznos.getText()));

                narudzbina.setKonobar(Sesija.getInstanca().getUlogovaniKonobar());
                narudzbina.setDatumNarucivanja(datumNarucivanja);

                Kontroler.getInstanca().dodajNarudzbinu(narudzbina);

                JOptionPane.showMessageDialog(this,
                        "Sistem je zapamtio narudzbinu.",
                        "Dodavanje narudzbine",
                        JOptionPane.INFORMATION_MESSAGE);

                this.dispose();
            } catch (GasenjeProgramaIzuzetak ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage(), "Upozorenje", JOptionPane.WARNING_MESSAGE);
                System.exit(0);
            } catch (ServerskiIzuzetak ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage(), "Greska prilikom dodavanja narudzbine", JOptionPane.ERROR_MESSAGE);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Doslo je do neocekivane greske prilikom dodavanja narudzbine.", "Greska prilikom dodavanja narudzbine", JOptionPane.ERROR_MESSAGE);
            }

        }
        // IZMENA
        if (status.equals(StatusForme.IZMENI)) {

            try {
                Narudzbina narudzbina = izabranaNarudzbina;
                ModelTabeleStavkaNarudzbine mts
                        = (ModelTabeleStavkaNarudzbine) tblStavkeNarudzbine.getModel();

                if (mts.getListaStavki().isEmpty()) {
                    throw new Exception("Narudžbina mora imati barem jednu stavku!");
                }
                SimpleDateFormat sdf = new SimpleDateFormat("dd.MM.yyyy");

                Date datumNarucivanja;
                try {
                    datumNarucivanja = sdf.parse(txtDatumNarucivanja.getText());
                } catch (ParseException ex) {
                    throw new Exception("Neispravan format datuma (dd.MM.yyyy)!");
                }
                narudzbina.setDatumNarucivanja(datumNarucivanja);
                narudzbina.setKonobar((Konobar) cmbKonobar.getSelectedItem());
                narudzbina.setGost((Gost) cmbGost.getSelectedItem());
                narudzbina.setNacinPlacanja((NacinPlacanja) cmbNacinPlacanja.getSelectedItem());
                narudzbina.setNapomena(txtNapomena.getText());
                narudzbina.setStavkeNarudzbine(mts.getListaStavki());

                narudzbina.setUkupanIznos(new BigDecimal(txtUkupanIznos.getText()));

                Kontroler.getInstanca().izmeniNarudzbinu(narudzbina);

                if (getParent() instanceof FormaZaPretraguNarudzbina) {
                    ((FormaZaPretraguNarudzbina) getParent()).srediTabelu();
                }

                JOptionPane.showMessageDialog(this,"Sistem je zapamtio narudzbinu.","Izmena", JOptionPane.INFORMATION_MESSAGE);
                this.dispose();

            } catch (GasenjeProgramaIzuzetak ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage(), "Upozorenje", JOptionPane.WARNING_MESSAGE);
                System.exit(0);
            } catch (ServerskiIzuzetak ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage(), "Greska prilikom izmene narudzbine", JOptionPane.ERROR_MESSAGE);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage(), "Greska prilikom izmene narudzbine", JOptionPane.ERROR_MESSAGE);
            }

        }
    }//GEN-LAST:event_btnDugmeActionPerformed

    private void btnOtkaziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOtkaziActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnOtkaziActionPerformed

    private void cmbNacinPlacanjaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbNacinPlacanjaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbNacinPlacanjaActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDodajStavkuNarudzbine;
    private javax.swing.JButton btnDugme;
    private javax.swing.JButton btnObrisiStavkuNarudzbine;
    private javax.swing.JButton btnOtkazi;
    private javax.swing.JComboBox cmbGost;
    private javax.swing.JComboBox<Object> cmbKonobar;
    private javax.swing.JComboBox<NacinPlacanja> cmbNacinPlacanja;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblDatumNarucivanja;
    private javax.swing.JLabel lblGost;
    private javax.swing.JLabel lblIDNarudzbenica;
    private javax.swing.JLabel lblKonobar;
    private javax.swing.JLabel lblNacinPlacanja;
    private javax.swing.JLabel lblNapomena;
    private javax.swing.JLabel lblUkupanIznos;
    private javax.swing.JTable tblArtikli;
    private javax.swing.JTable tblStavkeNarudzbine;
    private javax.swing.JFormattedTextField txtDatumNarucivanja;
    private javax.swing.JTextField txtIDNarudzbina;
    private javax.swing.JTextArea txtNapomena;
    private javax.swing.JTextField txtUkupanIznos;
    // End of variables declaration//GEN-END:variables

    private void pripremiFormu(StatusForme status) {
        setLocationRelativeTo(null);
        popuniGoste();
        srediTabeluArtikala();
        srediTabeluStavki();
        popuniKonobara();

        switch (status) {
            case DODAJ:
                btnDugme.setText("Sacuvaj narudzbinu");

                txtUkupanIznos.setEditable(false);
                cmbKonobar.setEnabled(false);

                txtIDNarudzbina.setVisible(false);
                lblIDNarudzbenica.setVisible(false);

                SimpleDateFormat sdf = new SimpleDateFormat("dd.MM.yyyy");
                txtDatumNarucivanja.setText(sdf.format(new Date()));

                setTitle("Forma za dodavanje narudzbine");
                break;
            case PRIKAZI:
                btnDugme.setText("Izmeni narudzbinu");
                txtIDNarudzbina.setEnabled(false);
                txtDatumNarucivanja.setEnabled(false);
                cmbNacinPlacanja.setEnabled(false);

                tblArtikli.setEnabled(false);
                btnDodajStavkuNarudzbine.setEnabled(false);
                tblStavkeNarudzbine.setEnabled(false);
                btnObrisiStavkuNarudzbine.setEnabled(false);

                txtUkupanIznos.setEnabled(false);
                txtNapomena.setEnabled(false);
                cmbKonobar.setEnabled(false);
                cmbGost.setEnabled(false);

                popuniPoljaZaIzabranuNarudzbinu(izabranaNarudzbina);
                break;
            case IZMENI:
                btnDugme.setText("Potvrdi izmene");
                txtUkupanIznos.setEnabled(false);
                txtIDNarudzbina.setEnabled(false);
                cmbKonobar.setEnabled(false);
                setTitle("Forma za izmenu narudzbine");
                popuniPoljaZaIzabranuNarudzbinu(izabranaNarudzbina);
                break;

        }
    }

    private void popuniGoste() {
        try {
            cmbGost.removeAllItems();
            List<Gost> sviGosti = Kontroler.getInstanca().vratiSveGoste();
            for (Gost gost : sviGosti) {
                cmbGost.addItem(gost);
            }
        } catch (GasenjeProgramaIzuzetak ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Upozorenje", JOptionPane.WARNING_MESSAGE);
            System.exit(0);
        } catch (ServerskiIzuzetak ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Greska prilikom ucitavanja liste gostiju", JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Doslo je do neocekivane greske prilikom ucitavanja liste gostiju.", "Greska", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void srediTabeluArtikala() {
        try {
            List<Artikal> listaArtikala = Kontroler.getInstanca().vratiSveArtikle();
            ModelTabeleArtikal modelTabeleArtikal = new ModelTabeleArtikal();
            tblArtikli.setModel(modelTabeleArtikal);
            modelTabeleArtikal.setListaArtikala(listaArtikala);

        } catch (GasenjeProgramaIzuzetak ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Upozorenje", JOptionPane.WARNING_MESSAGE);
            System.exit(0);
        } catch (ServerskiIzuzetak ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Greska prilikom ucitavanja liste artikala", JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Doslo je do neocekivane greske prilikom ucitavanja liste artikala.", "Greska", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void srediTabeluStavki() {
        ModelTabeleStavkaNarudzbine modelTabeleStavke = new ModelTabeleStavkaNarudzbine();
        tblStavkeNarudzbine.setModel(modelTabeleStavke);
        modelTabeleStavke.setTxtUkupanIznos(txtUkupanIznos);
    }

    private void popuniKonobara() {
        try {
            cmbKonobar.removeAllItems();
            List<Konobar> listaKonobara = Kontroler.getInstanca().vratiSveKonobare();
            for (Konobar k : listaKonobara) {
                cmbKonobar.addItem(k);
            }
            Konobar ulogovani = Sesija.getInstanca().getUlogovaniKonobar();
            cmbKonobar.setSelectedItem(ulogovani);

        } catch (GasenjeProgramaIzuzetak ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Upozorenje", JOptionPane.WARNING_MESSAGE);
            System.exit(0);
        } catch (ServerskiIzuzetak ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Greska prilikom ucitavanja liste konobara", JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Doslo je do neocekivane greske prilikom ucitavanja liste konobara.", "Greska", JOptionPane.ERROR_MESSAGE);
        }

    }

    private void popuniPoljaZaIzabranuNarudzbinu(Narudzbina narudzbina) {
        txtIDNarudzbina.setText(String.valueOf(narudzbina.getIdNarudzbina()));
        SimpleDateFormat sdf = new SimpleDateFormat("dd.MM.yyyy");
        txtDatumNarucivanja.setText(sdf.format(narudzbina.getDatumNarucivanja()));
        cmbGost.setSelectedItem(narudzbina.getGost());
        txtNapomena.setText(narudzbina.getNapomena());
        cmbKonobar.setSelectedItem(narudzbina.getKonobar());
        cmbNacinPlacanja.setSelectedItem(narudzbina.getNacinPlacanja());
        
        ModelTabeleStavkaNarudzbine modelTabeleStavke = new ModelTabeleStavkaNarudzbine();
        modelTabeleStavke.setTxtUkupanIznos(txtUkupanIznos);
        tblStavkeNarudzbine.setModel(modelTabeleStavke);
        modelTabeleStavke.dodajListuStavkiNarudzbina(narudzbina.getStavkeNarudzbine());

    }
}
