/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package forme;

import domen.Gost;
import domen.Konobar;
import domen.NacinPlacanja;
import domen.Narudzbina;
import izuzeci.GasenjeProgramaIzuzetak;
import izuzeci.ServerskiIzuzetak;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import kontroler.Kontroler;
import modeli.ModelTabeleNarudzbina;

/**
 *
 * @author Joska Stojanovic
 */
public class FormaZaPretraguNarudzbina extends javax.swing.JDialog {

    /**
     * Creates new form FormaZaPretraguNarudzbina
     */
    ModelTabeleNarudzbina modelTabeleNarudzbina;

    public FormaZaPretraguNarudzbina(GlavnaForma parent, boolean modal) {
        super(parent, modal);
        initComponents();
        pripremiFormu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNacinPlacanja = new javax.swing.JLabel();
        btnPretrazi = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblNarudzbine = new javax.swing.JTable();
        btnDetalji = new javax.swing.JButton();
        btnOtkazi = new javax.swing.JButton();
        cmbNacinPlacanja = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cmbKonobar = new javax.swing.JComboBox<>();
        cmbGost = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblNacinPlacanja.setText("Nacin placanja: ");

        btnPretrazi.setText("Pretrazi");
        btnPretrazi.addActionListener(this::btnPretraziActionPerformed);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Narudzbine"));

        tblNarudzbine.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblNarudzbine);

        btnDetalji.setText("Detalji o izabranoj narudzbini");
        btnDetalji.addActionListener(this::btnDetaljiActionPerformed);

        btnOtkazi.setText("Otkazi");
        btnOtkazi.addActionListener(this::btnOtkaziActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnOtkazi, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDetalji, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(20, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 766, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDetalji)
                    .addComponent(btnOtkazi))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        cmbNacinPlacanja.setModel(new DefaultComboBoxModel(NacinPlacanja.values()));
        cmbNacinPlacanja.setSelectedIndex(-1);

        jLabel1.setText("Gost: ");

        jLabel2.setText("Konobar: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblNacinPlacanja, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGap(18, 18, 18))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addGap(98, 98, 98)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(119, 119, 119)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmbNacinPlacanja, 0, 356, Short.MAX_VALUE)
                            .addComponent(cmbKonobar, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbGost, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(56, 56, 56)
                        .addComponent(btnPretrazi, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(118, 118, 118)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmbKonobar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(cmbGost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(btnPretrazi, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNacinPlacanja)
                    .addComponent(cmbNacinPlacanja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPretraziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPretraziActionPerformed
        Konobar izabraniKonobar= (Konobar) cmbKonobar.getSelectedItem();
        Gost izabraniGost=(Gost) cmbGost.getSelectedItem();
        NacinPlacanja izabraniNacin=(NacinPlacanja) cmbNacinPlacanja.getSelectedItem();
        
        if(izabraniGost==null && izabraniKonobar==null && izabraniNacin==null){
             JOptionPane.showMessageDialog(this, "Morate izabrati kriterijum prilikom pretrage narudzbine!", "Pretraga narudzbina", JOptionPane.WARNING_MESSAGE);
            return;
        }else{
                    List<Narudzbina> listaNarudzbina;
            try {
                listaNarudzbina = Kontroler.getInstanca().pretraziNarudzbinu(izabraniGost,izabraniKonobar,izabraniNacin);

                modelTabeleNarudzbina = new ModelTabeleNarudzbina();
                tblNarudzbine.setModel(modelTabeleNarudzbina);

                if (listaNarudzbina.isEmpty()) {
                    JOptionPane.showMessageDialog(this, "Sistem ne moze da pronadje narudzbine po zadatim kriterijumima.", "Greska prilikom pretrage narudzbina", JOptionPane.ERROR_MESSAGE);
                    return;
                } else {
                    JOptionPane.showMessageDialog(this, "Sistem je nasao narudzbine po zadatim kriterijumima.", "Pretraga narudzbina", JOptionPane.INFORMATION_MESSAGE);
                }

                modelTabeleNarudzbina.setListaNarudzbina(listaNarudzbina);

            } catch (GasenjeProgramaIzuzetak ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage(), "Upozorenje", JOptionPane.WARNING_MESSAGE);
                System.exit(0);
            } catch (ServerskiIzuzetak ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage(), "Greska prilikom pretrage narudzbina", JOptionPane.ERROR_MESSAGE);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Doslo je do neocekivane greske prilikom pretrage narudzbina.", "Greska", JOptionPane.ERROR_MESSAGE);
            }
        }
        
    }//GEN-LAST:event_btnPretraziActionPerformed

    private void btnDetaljiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetaljiActionPerformed
        int izabraniRed=tblNarudzbine.getSelectedRow();
        if(izabraniRed==-1){
            JOptionPane.showMessageDialog(this, "Morate izabrati narudzbinu iz tabele!", "Detalji o narudzbini", JOptionPane.WARNING_MESSAGE);
            return;
        }else{
            try {
                modelTabeleNarudzbina=(ModelTabeleNarudzbina) tblNarudzbine.getModel();
                Narudzbina izabranaNarudzbina=modelTabeleNarudzbina.vratiNarudzbinu(izabraniRed);
                
                Narudzbina narudzbina=Kontroler.getInstanca().vratiNarudzbinu(izabranaNarudzbina.getIdNarudzbina());
                JOptionPane.showMessageDialog(this, "Sistem je nasao narudzbinu.", "Detalji o narudzbini", JOptionPane.INFORMATION_MESSAGE);
                
                FormaNarudzbina formaNarudzbinaPrikaz= new FormaNarudzbina(this, true, StatusForme.PRIKAZI,narudzbina);
                formaNarudzbinaPrikaz.setVisible(true);
                
            } catch (GasenjeProgramaIzuzetak ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage(), "Upozorenje", JOptionPane.WARNING_MESSAGE);
                System.exit(0);
            } catch (ServerskiIzuzetak ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage(), "Greska prilikom ucitavanja narudzbine", JOptionPane.ERROR_MESSAGE);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Doslo je do neocekivane greske prilikom ucitavanja izabrane narudzbine.", "Greska prilikom ucitavanja narudzbine", JOptionPane.ERROR_MESSAGE);
            }
            
            
        }
    }//GEN-LAST:event_btnDetaljiActionPerformed

    private void btnOtkaziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOtkaziActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnOtkaziActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDetalji;
    private javax.swing.JButton btnOtkazi;
    private javax.swing.JButton btnPretrazi;
    private javax.swing.JComboBox<Object> cmbGost;
    private javax.swing.JComboBox<Object> cmbKonobar;
    private javax.swing.JComboBox cmbNacinPlacanja;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblNacinPlacanja;
    private javax.swing.JTable tblNarudzbine;
    // End of variables declaration//GEN-END:variables

    private void pripremiFormu() {
        setLocationRelativeTo(null);
        setTitle("Forma za pretragu narudzbina");
        popuniCmbKonobar();
        popuniCmbGost();
        srediTabelu();

    }

    private void popuniCmbKonobar() {
        try {
            cmbKonobar.removeAllItems();
            List<Konobar> listaKonobara = Kontroler.getInstanca().vratiSveKonobare();
            for (Konobar k : listaKonobara) {
                cmbKonobar.addItem(k);
            }
            cmbKonobar.setSelectedIndex(-1);
        } catch (GasenjeProgramaIzuzetak ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Upozorenje", JOptionPane.WARNING_MESSAGE);
            System.exit(0);
        } catch (ServerskiIzuzetak ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Greska prilikom ucitavanja konobara", JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Doslo je do neocekivane greske prilikom ucitavanja konobara.", "Greska", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void popuniCmbGost() {
        try {
            cmbGost.removeAllItems();
            List<Gost> listaGostiju = Kontroler.getInstanca().vratiSveGoste();
            for (Gost g : listaGostiju) {
                cmbGost.addItem(g);
            }
            cmbGost.setSelectedIndex(-1);
        } catch (GasenjeProgramaIzuzetak ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Upozorenje", JOptionPane.WARNING_MESSAGE);
            System.exit(0);
        } catch (ServerskiIzuzetak ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Greska prilikom ucitavanja gostiju", JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Doslo je do neocekivane greske prilikom ucitavanja gostiju.", "Greska", JOptionPane.ERROR_MESSAGE);
        }
    }

    public void srediTabelu() {
        try {
            List<Narudzbina> listaNarudzbina=Kontroler.getInstanca().vratiSveNarudzbine();
            modelTabeleNarudzbina= new ModelTabeleNarudzbina();
            tblNarudzbine.setModel(modelTabeleNarudzbina);
            modelTabeleNarudzbina.setListaNarudzbina(listaNarudzbina);
        } catch (GasenjeProgramaIzuzetak ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Upozorenje", JOptionPane.WARNING_MESSAGE);
            System.exit(0);
        } catch (ServerskiIzuzetak ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Greska prilikom ucitavanja narudzbina", JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Doslo je do neocekivane greske prilikom ucitavanja narudzbina.", "Greska", JOptionPane.ERROR_MESSAGE);
        }
        
    }
}
