/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forme;

import domen.Gost;
import domen.TipGosta;
import izuzeci.GasenjeProgramaIzuzetak;
import izuzeci.ServerskiIzuzetak;
import java.util.List;
import javax.swing.JOptionPane;
import kontroler.Kontroler;
import sesija.Sesija;

/**
 *
 * @author Joska Stojanovic
 */
public class GlavnaForma extends javax.swing.JFrame {

    /**
     * Creates new form GlavnaForma
     */
    public GlavnaForma() {
        initComponents();
        pripremiFormu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuBar4 = new javax.swing.JMenuBar();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        lblUlogovaniKonobar = new javax.swing.JLabel();
        txtUlogovaniKonobar = new javax.swing.JTextField();
        btnOdjaviSe = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        mGost = new javax.swing.JMenu();
        miKreirajNovogGosta = new javax.swing.JMenuItem();
        miPretraziGoste = new javax.swing.JMenuItem();
        mNarudzbina = new javax.swing.JMenu();
        miKreirajNarudzbinu = new javax.swing.JMenuItem();
        miPretraziNarudzbine = new javax.swing.JMenuItem();
        mKvalifikacija = new javax.swing.JMenu();
        miUbaciKvalifikaciju = new javax.swing.JMenuItem();

        jMenu1.setText("File");
        jMenuBar2.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar2.add(jMenu2);

        jMenu3.setText("File");
        jMenuBar3.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar3.add(jMenu4);

        jMenu5.setText("File");
        jMenuBar4.add(jMenu5);

        jMenu6.setText("Edit");
        jMenuBar4.add(jMenu6);

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblUlogovaniKonobar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblUlogovaniKonobar.setText("Prijavljeni konobar:");

        btnOdjaviSe.setText("Odjavi se");
        btnOdjaviSe.addActionListener(this::btnOdjaviSeActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnOdjaviSe, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(lblUlogovaniKonobar)
                        .addGap(42, 42, 42)
                        .addComponent(txtUlogovaniKonobar, javax.swing.GroupLayout.DEFAULT_SIZE, 429, Short.MAX_VALUE)))
                .addGap(17, 17, 17))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUlogovaniKonobar)
                    .addComponent(txtUlogovaniKonobar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnOdjaviSe)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        mGost.setText("Gost");

        miKreirajNovogGosta.setText("Kreiraj novog gosta");
        miKreirajNovogGosta.addActionListener(this::miKreirajNovogGostaActionPerformed);
        mGost.add(miKreirajNovogGosta);

        miPretraziGoste.setText("Pretrazi goste");
        miPretraziGoste.addActionListener(this::miPretraziGosteActionPerformed);
        mGost.add(miPretraziGoste);

        jMenuBar1.add(mGost);

        mNarudzbina.setText("Narudzbina");

        miKreirajNarudzbinu.setText("Ubaci narudzbinu");
        miKreirajNarudzbinu.addActionListener(this::miKreirajNarudzbinuActionPerformed);
        mNarudzbina.add(miKreirajNarudzbinu);

        miPretraziNarudzbine.setText("Pretrazi narudzbine");
        miPretraziNarudzbine.addActionListener(this::miPretraziNarudzbineActionPerformed);
        mNarudzbina.add(miPretraziNarudzbine);

        jMenuBar1.add(mNarudzbina);

        mKvalifikacija.setText("Kvalifikacija");

        miUbaciKvalifikaciju.setText("Ubaci kvalifikaciju");
        miUbaciKvalifikaciju.addActionListener(this::miUbaciKvalifikacijuActionPerformed);
        mKvalifikacija.add(miUbaciKvalifikaciju);

        jMenuBar1.add(mKvalifikacija);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(68, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOdjaviSeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOdjaviSeActionPerformed
        Object[] moguciOdgovori = {"Da", "Ne"};
        int potvrdaOdjave = JOptionPane.showOptionDialog(this, "Da li sigurno zelite da se odjavite sa sistema?",
                "Potvrda odjave", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE,
                null, moguciOdgovori, moguciOdgovori[0]);

        if (potvrdaOdjave == JOptionPane.YES_OPTION) {
            try {
                Kontroler.getInstanca().odjaviKonobara(Sesija.getInstanca().getUlogovaniKonobar());

                JOptionPane.showMessageDialog(this, "Uspesna odjava sa sistema.", "Odjava", JOptionPane.INFORMATION_MESSAGE);
                this.dispose();
                new FormaZaPrijavu().setVisible(true);
            } catch (GasenjeProgramaIzuzetak ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage(), "Upozorenje", JOptionPane.WARNING_MESSAGE);
                System.exit(0);
            } catch (ServerskiIzuzetak ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage(), "Greska prilikom odjave", JOptionPane.ERROR_MESSAGE);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Doslo je do neocekivane greske prilikom odjave sa sistema.", "Greska prilikom odjave", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            return;
        }
    }//GEN-LAST:event_btnOdjaviSeActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        JOptionPane.showMessageDialog(this, "Ukoliko zelite da se odjavite sa sistema, morate kliknuti na dugme Odjavi se.", "Upozorenje", JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_formWindowClosing

    private void miKreirajNovogGostaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miKreirajNovogGostaActionPerformed

        try {
            List<TipGosta> tipovi=Kontroler.getInstanca().vratiSveTipoveGosta();
            Gost gost = new Gost();
            gost.setTipGosta(tipovi.get(0));
            gost = Kontroler.getInstanca().dodajGosta(gost);
            JOptionPane.showMessageDialog(this, "Sistem je kreirao gosta.", "Dodavanje gosta", JOptionPane.INFORMATION_MESSAGE);
            new FormaGost(null, true, StatusForme.DODAJ, gost).setVisible(true);

        } catch (GasenjeProgramaIzuzetak ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Upozorenje", JOptionPane.WARNING_MESSAGE);
            System.exit(0);
        } catch (ServerskiIzuzetak ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Greska prilikom dodavanja gosta", JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Doslo je do neocekivane greske prilikom dodavanja novog gosta.", "Greska prilikom dodavanja gosta", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_miKreirajNovogGostaActionPerformed

    private void miUbaciKvalifikacijuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miUbaciKvalifikacijuActionPerformed
        new FormaKvalifikacija(this, true, StatusForme.DODAJ).setVisible(true);
    }//GEN-LAST:event_miUbaciKvalifikacijuActionPerformed

    private void miPretraziGosteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miPretraziGosteActionPerformed
        new FormaZaPretraguGostiju(this, true).setVisible(true);
    }//GEN-LAST:event_miPretraziGosteActionPerformed

    private void miKreirajNarudzbinuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miKreirajNarudzbinuActionPerformed
        new FormaNarudzbina(null, true, StatusForme.DODAJ,null).setVisible(true);
    }//GEN-LAST:event_miKreirajNarudzbinuActionPerformed

    private void miPretraziNarudzbineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miPretraziNarudzbineActionPerformed
        new FormaZaPretraguNarudzbina(this, true).setVisible(true);
    }//GEN-LAST:event_miPretraziNarudzbineActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOdjaviSe;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuBar jMenuBar4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblUlogovaniKonobar;
    private javax.swing.JMenu mGost;
    private javax.swing.JMenu mKvalifikacija;
    private javax.swing.JMenu mNarudzbina;
    private javax.swing.JMenuItem miKreirajNarudzbinu;
    private javax.swing.JMenuItem miKreirajNovogGosta;
    private javax.swing.JMenuItem miPretraziGoste;
    private javax.swing.JMenuItem miPretraziNarudzbine;
    private javax.swing.JMenuItem miUbaciKvalifikaciju;
    private javax.swing.JTextField txtUlogovaniKonobar;
    // End of variables declaration//GEN-END:variables

    private void pripremiFormu() {
        setLocationRelativeTo(null);
        setTitle("Glavna forma");
        txtUlogovaniKonobar.setText(Sesija.getInstanca().getUlogovaniKonobar().toString());
        txtUlogovaniKonobar.setEditable(false);
    }
}
