/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forme;

import db.Util;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.Properties;
import javax.swing.JOptionPane;

/**
 *
 * @author Joska Stojanovic
 */
public class FormaZaIzmenuKonfiguracije extends javax.swing.JDialog {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormaZaIzmenuKonfiguracije.class.getName());

    /**
     * Creates new form FormaZaIzmenuKonfiguracije
     */
    public FormaZaIzmenuKonfiguracije(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        pripremiFormu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblUrl = new javax.swing.JLabel();
        txtUrl = new javax.swing.JTextField();
        lblKorisnickoIme = new javax.swing.JLabel();
        txtKorisnickoIme = new javax.swing.JTextField();
        txtSifra = new javax.swing.JTextField();
        lblSifra = new javax.swing.JLabel();
        btnSacuvajKonfiguracijuBaze = new javax.swing.JButton();
        lblPort = new javax.swing.JLabel();
        txtPort = new javax.swing.JTextField();
        btnOtkazi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Konfiguracija"));

        lblUrl.setText("URL:");

        lblKorisnickoIme.setText("Korisnicko ime:");

        lblSifra.setText("Sifra:");

        btnSacuvajKonfiguracijuBaze.setText("Sacuvaj");
        btnSacuvajKonfiguracijuBaze.addActionListener(this::btnSacuvajKonfiguracijuBazeActionPerformed);

        lblPort.setText("Port:");

        btnOtkazi.setText("Otkazi");
        btnOtkazi.addActionListener(this::btnOtkaziActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnOtkazi, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSacuvajKonfiguracijuBaze, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblSifra)
                                    .addComponent(lblKorisnickoIme))
                                .addGap(69, 69, 69))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblUrl)
                                    .addComponent(lblPort))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtKorisnickoIme, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSifra, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtUrl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                            .addComponent(txtPort, javax.swing.GroupLayout.Alignment.LEADING))))
                .addGap(12, 12, 12))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPort)
                    .addComponent(txtPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUrl)
                    .addComponent(txtUrl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblKorisnickoIme)
                    .addComponent(txtKorisnickoIme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSifra)
                    .addComponent(txtSifra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSacuvajKonfiguracijuBaze)
                    .addComponent(btnOtkazi))
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSacuvajKonfiguracijuBazeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSacuvajKonfiguracijuBazeActionPerformed
        String port = txtPort.getText().trim();
        String url = txtUrl.getText().trim();
        String korisnickoIme = txtKorisnickoIme.getText().trim();
        String sifra = txtSifra.getText().trim();

        if (port.isEmpty() || url.isEmpty() || korisnickoIme.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Morate popuniti sva polja prilikom konfiguracije!", "", JOptionPane.WARNING_MESSAGE);
            return;
        }
        // PROVERA PORTA
        int portBroj;
        try {
            portBroj = Integer.parseInt(port);

            if (portBroj < 0 || portBroj > 65535) {
                JOptionPane.showMessageDialog(this, "Port mora biti u opsegu 0-65535!", "", JOptionPane.WARNING_MESSAGE);
                return;
            }

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Port mora biti broj!", "", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            Util.getInstanca().setPort(port);
            Util.getInstanca().setUrl(url);
            Util.getInstanca().setUser(korisnickoIme);
            Util.getInstanca().setPassword(sifra);

            FileOutputStream out = new FileOutputStream("config/config.properties");
            Util.getInstanca().setOut(out);
            Util.getInstanca().store();
            Util.getInstanca().zatvoriOut();

            JOptionPane.showMessageDialog(this, "Uspesno ste izmenili konfiguraciju!");
            this.dispose();
        } catch (FileNotFoundException ex) {
            System.out.println("Propeti fajl pod nazivom config.properties nije pronadjen.");
            ex.printStackTrace();
        } catch (IOException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnSacuvajKonfiguracijuBazeActionPerformed

    private void btnOtkaziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOtkaziActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnOtkaziActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOtkazi;
    private javax.swing.JButton btnSacuvajKonfiguracijuBaze;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblKorisnickoIme;
    private javax.swing.JLabel lblPort;
    private javax.swing.JLabel lblSifra;
    private javax.swing.JLabel lblUrl;
    private javax.swing.JTextField txtKorisnickoIme;
    private javax.swing.JTextField txtPort;
    private javax.swing.JTextField txtSifra;
    private javax.swing.JTextField txtUrl;
    // End of variables declaration//GEN-END:variables

    private void pripremiFormu() {
        try {
            setLocationRelativeTo(null);
            setTitle("Forma za izmenu konfiguracije");
            txtPort.setText(Util.getInstanca().getPort());
            txtKorisnickoIme.setText(Util.getInstanca().getUser());
            txtSifra.setText(Util.getInstanca().getPassword());
            txtUrl.setText(Util.getInstanca().getUrl());
        } catch (IOException ex) {
            System.getLogger(FormaZaIzmenuKonfiguracije.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }

    }
}
