/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forme;

import db.Util;
import javax.swing.JOptionPane;
import kontroler.Kontroler;
import modeli.ModelTabeleKonobar;
import niti.PokretanjeServera;

/**
 *
 * @author Joska Stojanovic
 */
public class ServerskaForma extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ServerskaForma.class.getName());
    private PokretanjeServera pokretanjeServera;

    /**
     * Creates new form ServerskaForma
     */
    public ServerskaForma() {
        initComponents();
        pripremiFormu();

        Kontroler.getInstanca().setServerskaForma(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtStatusServera = new javax.swing.JTextField();
        btnPokreniServer = new javax.swing.JButton();
        btnUgasiServer = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblUlogovaniKonobari = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        mKonfiguracija = new javax.swing.JMenu();
        miIzmeniKonfiguraciju = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Status servera: ");

        btnPokreniServer.setText("Pokreni server");
        btnPokreniServer.addActionListener(this::btnPokreniServerActionPerformed);

        btnUgasiServer.setText("Ugasi server");
        btnUgasiServer.addActionListener(this::btnUgasiServerActionPerformed);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Lista ulogovanih konobara"));
        jPanel1.setName(""); // NOI18N

        tblUlogovaniKonobari.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblUlogovaniKonobari);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(102, 102, 102))
        );

        mKonfiguracija.setText("Konfiguracija");

        miIzmeniKonfiguraciju.setText("Izmeni konfiguraciju");
        miIzmeniKonfiguraciju.addActionListener(this::miIzmeniKonfiguracijuActionPerformed);
        mKonfiguracija.add(miIzmeniKonfiguraciju);

        jMenuBar1.add(mKonfiguracija);
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnPokreniServer, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnUgasiServer, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(txtStatusServera, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(0, 14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtStatusServera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUgasiServer)
                    .addComponent(btnPokreniServer))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miIzmeniKonfiguracijuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miIzmeniKonfiguracijuActionPerformed
        new FormaZaIzmenuKonfiguracije(this, true).setVisible(true);
    }//GEN-LAST:event_miIzmeniKonfiguracijuActionPerformed

    private void btnPokreniServerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPokreniServerActionPerformed
        try {
            if (Util.getInstanca().daLiJePrazanProperti()) {
                JOptionPane.showMessageDialog(this, "Property fajl je prazan. Morate uneti podatke za konfiguraciju!", "", JOptionPane.WARNING_MESSAGE);
                return;
            }
        } catch (Exception e) {
            System.out.println("Doslo je do greske prilikom pretrage properti fajla.");
            e.printStackTrace();
        }
        if (pokretanjeServera.isPokrenut() == false) {
            pokretanjeServera = new PokretanjeServera();
            pokretanjeServera.start();
            pokretanjeServera.setPokrenut(true);
            serverJePokrenut();
            mKonfiguracija.setEnabled(false);
        }
    }//GEN-LAST:event_btnPokreniServerActionPerformed

    private void btnUgasiServerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUgasiServerActionPerformed
        if (pokretanjeServera.isPokrenut() == true) {
            pokretanjeServera.setPokrenut(false);
            pokretanjeServera.prekiniKlijentskePrograme();

            serverJeUgasen();
            mKonfiguracija.setEnabled(true);
        }
    }//GEN-LAST:event_btnUgasiServerActionPerformed
    private void formWindowClosed(java.awt.event.WindowEvent evt) {
        if (pokretanjeServera.isPokrenut() == true) {
            pokretanjeServera.prekiniKlijentskePrograme();
        }

        // Kontroler.getInstanca().ocistiListuUlogovanihFarmaceuta();
    }

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPokreniServer;
    private javax.swing.JButton btnUgasiServer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenu mKonfiguracija;
    private javax.swing.JMenuItem miIzmeniKonfiguraciju;
    private javax.swing.JTable tblUlogovaniKonobari;
    private javax.swing.JTextField txtStatusServera;
    // End of variables declaration//GEN-END:variables

    private void pripremiFormu() {
        setLocationRelativeTo(null);
        setTitle("Serverski program");

        txtStatusServera.setText("Serverski program nije pokrenut.");
        txtStatusServera.setEditable(false);
        btnPokreniServer.setEnabled(true);
        btnUgasiServer.setEnabled(false);

        srediTabelu();
    }

    private void srediTabelu() {
        ModelTabeleKonobar mtk = new ModelTabeleKonobar();
        tblUlogovaniKonobari.setModel(mtk);
    }

    private void serverJePokrenut() {
        txtStatusServera.setText("Serverski program je pokrenut!");
        btnPokreniServer.setEnabled(false);
        btnUgasiServer.setEnabled(true);
    }

    private void serverJeUgasen() {
        txtStatusServera.setText("Serverski program je ugasen.");
        btnPokreniServer.setEnabled(true);
        btnUgasiServer.setEnabled(false);
        Kontroler.getInstanca().ocistiListuUlogovanihKonobara();
        srediTabelu();
    }

    public ModelTabeleKonobar vratiTabeluUlogovanihKonobara() {
        return (ModelTabeleKonobar) tblUlogovaniKonobari.getModel();
    }

}
